export var nodes = [
        { 
            id: 1, 
            label: 'HOTTIP', 
            title: 'Description of HOTTIP', 
            value: 10, 
            group: 1, 
            x: -100, 
            y: 100 
        },
        { 
            id: 2, 
            label: 'HOTAIRM1', 
            title: 'Description of HOTAIRM1', 
            value: 10, 
            group: 1, 
            x: -50, 
            y: 50 
        },
        { 
            id: 3, 
            label: 'HOXA11-AS', 
            title: 'Description of HOXA11-AS', 
            value: 10, 
            group: 1, 
            x: 0, 
            y: 0 
        },
        { 
            id: 4, 
            label: 'HOTAIR', 
            title: 'Description of HOTAIR', 
            value: 10, 
            group: 1, 
            x: 50, 
            y: -50 
        },
        { 
            id: 5, 
            label: 'HEIH', 
            title: 'Description of HEIH', 
            value: 10, 
            group: 1, 
            x: 100, 
            y: -100 
        },
        { 
            id: 6, 
            label: 'LBX2-AS1', 
            title: 'Description of LBX2-AS1', 
            value: 10, 
            group: 1, 
            x: 150, 
            y: -150 
        },
        { 
            id: 7, 
            label: 'LEF1-AS1', 
            title: 'Description of LEF1-AS1', 
            value: 10, 
            group: 1, 
            x: 200, 
            y: -200 
        },
// Diseases

        { 
            id: 8, 
            label: 'Osteosarcoma', 
            title: '', 
            value: 10, 
            group: 2, 
            x: 200, 
            y: -200 
        },
        { 
            id: 9, 
            label: 'Glioma', 
            title: '', 
            value: 10, 
            group: 2, 
            x: 200, 
            y: -200 
        },
        { 
            id: 10, 
            label: 'Retinoblastoma', 
            title: '', 
            value: 10, 
            group: 2, 
            x: 200, 
            y: -200 
        },
        { 
            id: 11, 
            label: 'stomach carcinoma', 
            title: '', 
            value: 10, 
            group: 2, 
            x: 200, 
            y: -200 
        },
        {'id': 12, 'label': 'Nasopharyngeal Neoplasms', 'title': 'Description of Nasopharyngeal Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 13, 'label': 'Arthritis, Rheumatoid', 'title': 'Description of Arthritis, Rheumatoid', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 14, 'label': 'Mouth Neoplasms', 'title': 'Description of Mouth Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 15, 'label': 'Squamous Cell Carcinoma of Head and Neck', 'title': 'Description of Squamous Cell Carcinoma of Head and Neck', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 16, 'label': 'Lung Diseases', 'title': 'Description of Lung Diseases', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 17, 'label': 'Stomach Neoplasms', 'title': 'Description of Stomach Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 18, 'label': 'Breast Neoplasms', 'title': 'Description of Breast Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 19, 'label': 'Carcinoma, Non-Small-Cell Lung', 'title': 'Description of Carcinoma, Non-Small-Cell Lung', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 20, 'label': 'Carcinoma, Hepatocellular', 'title': 'Description of Carcinoma, Hepatocellular', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 21, 'label': 'Ovarian Neoplasms', 'title': 'Description of Ovarian Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 22, 'label': 'Leukemia, Myeloid, Acute', 'title': 'Description of Leukemia, Myeloid, Acute', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 23, 'label': 'pancreatic ductal adenocarcinoma', 'title': 'Description of pancreatic ductal adenocarcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 24, 'label': 'Glioblastoma', 'title': 'Description of Glioblastoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 25, 'label': 'Thyroid Neoplasms', 'title': 'Description of Thyroid Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 26, 'label': 'Parkinson Disease', 'title': 'Description of Parkinson Disease', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 27, 'label': 'Atherosclerosis', 'title': 'Description of Atherosclerosis', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 28, 'label': 'Colorectal Neoplasms', 'title': 'Description of Colorectal Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 29, 'label': 'Thyroid Cancer, Papillary', 'title': 'Description of Thyroid Cancer, Papillary', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 30, 'label': 'Carcinoma, Renal Cell', 'title': 'Description of Carcinoma, Renal Cell', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 31, 'label': 'Colonic Neoplasms', 'title': 'Description of Colonic Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 32, 'label': 'Osteoarthritis', 'title': 'Description of Osteoarthritis', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 33, 'label': 'pancreatic adenocarcinoma', 'title': 'Description of pancreatic adenocarcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 34, 'label': 'Adenocarcinoma of Lung', 'title': 'Description of Adenocarcinoma of Lung', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 35, 'label': 'Prostatic Neoplasms', 'title': 'Description of Prostatic Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 36, 'label': 'Thyroid Carcinoma, Anaplastic', 'title': 'Description of Thyroid Carcinoma, Anaplastic', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 37, 'label': 'Endometrial Neoplasms', 'title': 'Description of Endometrial Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 38, 'label': 'Liver Neoplasms', 'title': 'Description of Liver Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 39, 'label': 'Skin Neoplasms', 'title': 'Description of Skin Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 40, 'label': 'Keloid', 'title': 'Description of Keloid', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 41, 'label': 'skin melanoma', 'title': 'Description of skin melanoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 42, 'label': 'Demyelinating Diseases', 'title': 'Description of Demyelinating Diseases', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 43, 'label': 'Esophageal Squamous Cell Carcinoma', 'title': 'Description of Esophageal Squamous Cell Carcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 44, 'label': 'Triple Negative Breast Neoplasms', 'title': 'Description of Triple Negative Breast Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 45, 'label': 'esophageal carcinoma', 'title': 'Description of esophageal carcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 46, 'label': 'Cholangiocarcinoma', 'title': 'Description of Cholangiocarcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 47, 'label': 'Pre-Eclampsia', 'title': 'Description of Pre-Eclampsia', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 48, 'label': 'Psoriasis', 'title': 'Description of Psoriasis', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 49, 'label': 'Diabetic Retinopathy', 'title': 'Description of Diabetic Retinopathy', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 50, 'label': 'Sarcoma, Synovial', 'title': 'Description of Sarcoma, Synovial', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 51, 'label': 'Uterine Cervical Neoplasms', 'title': 'Description of Uterine Cervical Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 52, 'label': 'Non-alcoholic Fatty Liver Disease', 'title': 'Description of Non-alcoholic Fatty Liver Disease', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 53, 'label': 'Pulmonary Disease, Chronic Obstructive', 'title': 'Description of Pulmonary Disease, Chronic Obstructive', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 54, 'label': 'Nasopharyngeal carcinoma', 'title': 'Description of Nasopharyngeal carcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 55, 'label': 'Medulloblastoma', 'title': 'Description of Medulloblastoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 56, 'label': 'Esophageal Neoplasms', 'title': 'Description of Esophageal Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 57, 'label': 'Diabetic Nephropathies', 'title': 'Description of Diabetic Nephropathies', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 58, 'label': 'Endometriosis', 'title': 'Description of Endometriosis', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 59, 'label': 'Multiple Myeloma', 'title': 'Description of Multiple Myeloma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 60, 'label': 'Spinal Cord Injuries', 'title': 'Description of Spinal Cord Injuries', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 61, 'label': 'Adrenocortical Carcinoma', 'title': 'Description of Adrenocortical Carcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 62, 'label': 'lung non-small cell carcinoma', 'title': 'Description of lung non-small cell carcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 63, 'label': 'Subarachnoid Hemorrhage', 'title': 'Description of Subarachnoid Hemorrhage', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 64, 'label': 'Leukemia', 'title': 'Description of Leukemia', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 65, 'label': 'Carcinoma, Ductal, Breast', 'title': 'Description of Carcinoma, Ductal, Breast', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 66, 'label': 'Lung Neoplasms', 'title': 'Description of Lung Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 67, 'label': 'Leukemia, Lymphocytic, Chronic, B-Cell', 'title': 'Description of Leukemia, Lymphocytic, Chronic, B-Cell', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 68, 'label': 'Primary Ovarian Insufficiency', 'title': 'Description of Primary Ovarian Insufficiency', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 69, 'label': 'Ependymoma', 'title': 'Description of Ependymoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 70, 'label': 'Lupus Erythematosus, Discoid', 'title': 'Description of Lupus Erythematosus, Discoid', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 71, 'label': 'Neuroendocrine Tumors', 'title': 'Description of Neuroendocrine Tumors', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 72, 'label': 'Abortion, Habitual', 'title': 'Description of Abortion, Habitual', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 73, 'label': 'Stroke', 'title': 'Description of Stroke', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 74, 'label': 'RNA, Long Noncoding', 'title': 'Description of RNA, Long Noncoding', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 75, 'label': 'Leukemia, Myelogenous, Chronic, BCR-ABL Positive', 'title': 'Description of Leukemia, Myelogenous, Chronic, BCR-ABL Positive', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 76, 'label': 'transitional cell carcinoma', 'title': 'Description of transitional cell carcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 77, 'label': 'Urinary Bladder Neoplasms', 'title': 'Description of Urinary Bladder Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 78, 'label': 'Pancreatic Neoplasms', 'title': 'Description of Pancreatic Neoplasms', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 79, 'label': 'Lupus Erythematosus, Systemic', 'title': 'Description of Lupus Erythematosus, Systemic', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 80, 'label': 'Diabetes Mellitus, Type 2', 'title': 'Description of Diabetes Mellitus, Type 2', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 81, 'label': 'Coronary Artery Disease', 'title': 'Description of Coronary Artery Disease', 'value': 10, 'group': 2, 'x': 0, 'y': 0},
        {'id': 82, 'label': 'gastric adenocarcinoma', 'title': 'Description of gastric adenocarcinoma', 'value': 10, 'group': 2, 'x': 0, 'y': 0}
]


export var edges = [
    {'from': 1, 'to': 8},
{'from': 1, 'to': 9},
{'from': 1, 'to': 10},
{'from': 1, 'to': 11},
{'from': 1, 'to': 12},
{'from': 1, 'to': 13},
{'from': 1, 'to': 14},
{'from': 1, 'to': 15},
{'from': 1, 'to': 16},
{'from': 1, 'to': 22},
{'from': 1, 'to': 18},
{'from': 1, 'to': 28},
{'from': 1, 'to': 29},
{'from': 1, 'to': 30},
{'from': 1, 'to': 21},
{'from': 1, 'to': 19},
{'from': 1, 'to': 35},
{'from': 1, 'to': 64},
{'from': 1, 'to': 65},
{'from': 2, 'to': 17},
{'from': 2, 'to': 18},
{'from': 2, 'to': 19},
{'from': 2, 'to': 20},
{'from': 2, 'to': 21},
{'from': 2, 'to': 15},
{'from': 2, 'to': 22},
{'from': 2, 'to': 23},
{'from': 2, 'to': 24},
{'from': 2, 'to': 25},
{'from': 2, 'to': 29},
{'from': 2, 'to': 34},
{'from': 2, 'to': 35},
{'from': 2, 'to': 36},
{'from': 2, 'to': 37},
{'from': 2, 'to': 38},
{'from': 2, 'to': 43},
{'from': 2, 'to': 66},
{'from': 2, 'to': 28},
{'from': 2, 'to': 30},
{'from': 3, 'to': 26},
{'from': 3, 'to': 27},
{'from': 3, 'to': 39},
{'from': 3, 'to': 40},
{'from': 3, 'to': 20},
{'from': 3, 'to': 21},
{'from': 3, 'to': 15},
{'from': 3, 'to': 8},
{'from': 3, 'to': 9},
{'from': 3, 'to': 34},
{'from': 3, 'to': 35},
{'from': 3, 'to': 41},
{'from': 3, 'to': 42},
{'from': 3, 'to': 19},
{'from': 3, 'to': 18},
{'from': 3, 'to': 17},
{'from': 3, 'to': 28},
{'from': 3, 'to': 51},
{'from': 3, 'to': 61},
{'from': 3, 'to': 62},
{'from': 3, 'to': 63},
{'from': 4, 'to': 8},
{'from': 4, 'to': 19},
{'from': 4, 'to': 28},
{'from': 4, 'to': 31},
{'from': 4, 'to': 29},
{'from': 4, 'to': 30},
{'from': 4, 'to': 32},
{'from': 4, 'to': 20},
{'from': 4, 'to': 15},
{'from': 4, 'to': 33},
{'from': 4, 'to': 18},
{'from': 4, 'to': 17},
{'from': 4, 'to': 26},
{'from': 4, 'to': 22},
{'from': 4, 'to': 39},
{'from': 4, 'to': 47},
{'from': 4, 'to': 48},
{'from': 4, 'to': 49},
{'from': 4, 'to': 50},
{'from': 4, 'to': 51},
{'from': 4, 'to': 52},
{'from': 4, 'to': 53},
{'from': 4, 'to': 23},
{'from': 4, 'to': 54},
{'from': 4, 'to': 24},
{'from': 4, 'to': 25},
{'from': 4, 'to': 55},
{'from': 4, 'to': 46},
{'from': 4, 'to': 10},
{'from': 4, 'to': 38},
{'from': 4, 'to': 56},
{'from': 4, 'to': 57},
{'from': 4, 'to': 58},
{'from': 4, 'to': 13},
{'from': 4, 'to': 44},
{'from': 4, 'to': 59},
{'from': 4, 'to': 68},
{'from': 4, 'to': 9},
{'from': 4, 'to': 69},
{'from': 4, 'to': 70},
{'from': 4, 'to': 71},
{'from': 4, 'to': 72},
{'from': 4, 'to': 73},
{'from': 4, 'to': 74},
{'from': 4, 'to': 75},
{'from': 4, 'to': 76},
{'from': 4, 'to': 43},
{'from': 4, 'to': 21},
{'from': 4, 'to': 77},
{'from': 4, 'to': 78},
{'from': 4, 'to': 34},
{'from': 4, 'to': 79},
{'from': 4, 'to': 80},
{'from': 4, 'to': 81},
{'from': 4, 'to': 82},
{'from': 5, 'to': 17},
{'from': 5, 'to': 18},
{'from': 5, 'to': 19},
{'from': 5, 'to': 43},
{'from': 5, 'to': 21},
{'from': 5, 'to': 44},
{'from': 5, 'to': 45},
{'from': 5, 'to': 46},
{'from': 5, 'to': 10},
{'from': 5, 'to': 11},
{'from': 5, 'to': 81},
{'from': 6, 'to': 17},
{'from': 6, 'to': 19},
{'from': 6, 'to': 43},
{'from': 6, 'to': 31},
{'from': 6, 'to': 21},
{'from': 6, 'to': 9},
{'from': 6, 'to': 25},
{'from': 6, 'to': 59},
{'from': 7, 'to': 17},
{'from': 7, 'to': 28},
{'from': 7, 'to': 31},
{'from': 7, 'to': 20},
{'from': 7, 'to': 21},
{'from': 7, 'to': 15},
{'from': 7, 'to': 9},
{'from': 7, 'to': 19},
{'from': 7, 'to': 10},
{'from': 7, 'to': 22},
{'from': 7, 'to': 35},
{'from': 7, 'to': 60},
{'from': 7, 'to': 43},
{'from': 7, 'to': 67}
]







